@startuml Hotel Booking Use Case Diagram
top to bottom direction

rectangle "Hotel Booking" as HB{
    usecase "Register" as reg
    usecase "Login" as logIn
    usecase "Logout" as logOut
    usecase "View\nHotels" as viewHotel
    usecase "Manage\nHotels" as manageHotel
    usecase "View\nbookings" as viewBooking
    usecase "Manage\nbookings" as manageBookings
    usecase "View\nrooms" as viewrooms
    usecase "Manage\nrooms" as managerooms
}
user -- reg
user -- logIn
user -- logOut
user -- viewHotel
user -- viewBooking
user -- manageBookings
user -- viewrooms


reg -- admin
logIn -- admin
logOut -- admin
manageHotel -- admin
viewHotel -- admin
viewBooking -- admin
manageBookings -- admin
viewrooms -- admin
managerooms -- admin


@enduml