@startuml Manage Room (DELETE)

header Hotel Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Room (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:rooms" as routerRooms
participant "<<middleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:rooms" as controllersRoom
participant "<<model>>\n:Room" as modelRoom
database "<<MongoDB>>\n:room" as RoomDatabase

client->server ++:req.delete('/rooms/:id')
server->routerRooms ++:app.use('/rooms/:id', rooms)
routerRooms -> authMiddleware ++:protect()
routerRooms -> authMiddleware :authorize('admin')
routerRooms -> controllersRoom ++:deleteRoom()
controllersRoom->modelRoom ++:findById(req.params.id)
controllersRoom->modelRoom ++:delete(req.body)
modelRoom ->RoomDatabase ++: RoomSchema
RoomDatabase --> modelRoom --: room
controllersRoom <-- modelRoom --:room
controllersRoom->client --:response

@enduml