@startuml Manage Room (GET ALL)

header Hotel Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Room (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:rooms" as routerRooms
participant "<<middleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:rooms" as controllersRoom
participant "<<model>>\n:Room" as modelRoom
database "<<MongoDB>>\n:room" as RoomDatabase

client->server ++:req.get('/rooms')
server->routerRooms ++:app.use('/rooms', rooms)
routerRooms -> authMiddleware ++:protect()
routerRooms -> controllersRoom ++:getRooms()
controllersRoom->modelRoom ++:find()
modelRoom ->RoomDatabase ++: RoomSchema
RoomDatabase --> modelRoom --: room
controllersRoom <-- modelRoom --:room
controllersRoom->client --:response

@enduml